config/routes.rb
Cockteles::Application.routes.draw do

  root 'welcome#index'

  resources :cocktails
  resources :ingredients

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :dosages, dependent: :destroy
  accepts_nested_attributes_for :dosages, reject_if: proc {|attr| attr[:quantity].blank?}
  has_many :ingredients, :through => :dosages
end

app/models/dosage.rb
class Dosage < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :dosages, dependent: :destroy
  has_many :cocktails, :through => :dosages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
    @ingredients = Ingredient.all
    1.times { @cocktail.dosages.build }
  end

  # GET /cocktails/1/edit
  def edit
    @ingredients = Ingredient.all
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cocktail }
      else
        format.html { render action: 'new' }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :picture, :description, dosages_attributes: [:quantity, :cocktail_id])
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

def index
  @ingredients = Ingredient.all
end

def new
  @ingredient = Ingredient.new
end

def create
  @ingredient = Ingredient.create(ingredient_params)
  redirect_to ingredients_path
end

def destroy
  ingredient = Ingredient.find(params[:id])
  ingredient.destroy
  redirect_to ingredients_path
end

end


private

def ingredient_params
  params.require(:ingredient).permit(:name)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cocktails/_form.html.erb
<%= form_for(@cocktail) do |f| %>
  <% if @cocktail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
      <% @cocktail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">

<div> Ingrédients: </div>

  <ul>
    <% @ingredients.each do |ingredient| %>
      <li>
        <%= ingredient.name %>
      </li>
      <li>
        <%= f.fields_for :dosages do |dosage_f| %>
          <%= dosage_f.hidden_field :cocktail_id, value: @cocktail.id %>
          <%= "quantité de #{ingredient.name}" %>
          <%= dosage_f.text_field :quantity %>
        <% end %>
      </li>
    <% end %>
  </ul>




  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing cocktail</h1>

<%= render 'form' %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<h1>All our cocktails</h1>

<%= link_to 'New Cocktail', new_cocktail_path %>
<br>
<%= link_to 'Display ingredients available', ingredients_path %>
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= image_tag(cocktail.picture, size: "100x100") %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
        <td><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cocktails/new.html.erb
<h1>New cocktail</h1>

<%= render 'form' %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<!-- STILL NEED TO FIX IMAGE PROPORTIONS ISSUE -->

<p id="notice"><%= notice %></p>

<p>
  <strong>
    <%= @cocktail.name %>
  </strong>
</p>

<p>
  <%= image_tag(@cocktail.picture, size: "400x400") %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cocktail.description %>
</p>

<p>
  <strong>Recette:</strong>
  <ul><% @cocktail.dosages.each do |dosage| %>
      <li><%= "#{dosage.quantity} of #{dosage.ingredient.name}" %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/index.html.erb
<h1> Ingredients available</h1>

<table>
  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td>
          <%= ingredient.name %>
          <td><%= link_to 'Delete', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>
<br>
<%= link_to 'Back', cocktails_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Tous ensemble!</h1>
<div></div>
  <iframe width="420" height="315" src="//www.youtube-nocookie.com/embed/HjFx6Lpt-7w?rel=0" frameborder="0" allowfullscreen></iframe>
</div >
<div>
  <%= link_to "viens don' t'la coller mon petit gars", cocktails_path, class: 'my-link' %>
</div>